### ISSUE TITLE
optimize navigation 

### ISSUE THREAD

**Issue by krrisis** [AragonDAC/aragondac-website#12]
1) Only have 4 elements in nav (bcs you removed one title) & change to new (!) titles:

What We Do - How You Can Help - Who We Are - Join Us (So change 'Flock' to 'Vote' & remove 'social')

2) 
- Change title 'Meet our team' into 'Who We Are'
- Put this is same size as two previous & next title 

3) 

Is it possible to put the two icons of Riot & Rocket chat smaller to +/- the size of the social logos below? 

4) 
Add one sentence to the last textblock: 'Join us on Twitter, Medium, Github, YouTube and the Giveth DApp.

5) 
Move the Giveth icon to the right 

thx!

**Comment by MaxSemenchuk** [comment]
Pls check @krrisis

**Comment by krrisis** [comment]
Looks great! Things I still see: 

- What We Do -> still add capitals here
- maybe put the links under the two text blocks in the same way:
-- 1st block: Read our launch post --> 'Read our' not hyperlinked
-- 2nd: Read all about it in our Flock proposal right here. --> Remove the period at the end
- 'Who We Are' title still seems bigger than the others? 
- Aragon fight for freedom vid is no longer centered? 

thx!!

**Comment by MaxSemenchuk** [comment]
check now pls.
for me the video is centered, could you send me a screenshot if it repeats

**Comment by krrisis** [comment]
all perfect now!
