### ISSUE TITLE
add top nav 

### ISSUE THREAD

**Issue by krrisis** [AragonDAC/aragondac-website#3]
To make clearer that there is more content 'below the fold'.

Words: 

Join - leads to #join (button lower on the page)
Community #community (first block lower on the page)
Flock #community (first block lower on the page)
Team #team (second block lower on the page)
Social #social (last block on the page)

On mobile this will prob need to be a hamburger menu

**Comment by MaxSemenchuk** [comment]
Done

**Comment by krrisis** [comment]
Great! However, it only shows if you start scrolling (quite a bit), is it possible to show a transparent version also when you don't scroll? (bcs that's ofc also the added value - that people immediately see there is more)

**Comment by MaxSemenchuk** [comment]
ok, done

**Comment by krrisis** [comment]
purrrfect!!!
