### ISSUE TITLE
replace moving background by a static galaxy one 

### ISSUE THREAD

**Issue by krrisis** [AragonDAC/aragondac-website#5]
Similar to this one, but then with the aragon dac logo or logotype: https://wiki.aragon.org/design/artwork/basic/08.jpg

Discussed this with tatu and he also prefers this: in the future we want to build out a brand that sends out 'community', so warmer than aragon, so this 'static' in the background is not really very 'dac'-y

the galaxy makes sense as the aragon dac is part of the giveth galaxy, also used on giveth, and also used by aragon = good link.

some free images you could use here https://unsplash.com/search/photos/galaxy 

For a future version we can work on a real brand design for the dac but this is too short notice

**Comment by MaxSemenchuk** [comment]
@krrisis pls check – is it better now?

**Comment by krrisis** [comment]
Ooooooowwww!!! haha yes, I love it!! that's the best of both worlds - thx @MaxSemenchuk <3
