### ISSUE TITLE
Create a proper 'join' block

### ISSUE THREAD

**Issue by krrisis** [AragonDAC/aragondac-website#7]
Hey @MaxSemenchuk - so we need to change this one a bit to give people the full choice to choose between rocket & riot chat - hope this is clear? if not, tag/ping me!

- you can redirect the top nav ànd the 'join' button to a #join section which you create lower on the page (unless you prefer to create a subpage, you decide what works best ofc) 

- If on the same page I propose to put that block between the video and 'find us on social'

- Block should contain the following: 

a) rocket chat logo + a 'Join us on Rocket Chat' --> link to https://aragon.chat/channel/aragondac
b) riot logo + a 'Join us on Riot Chat' --> link to #1 

Maybe add a sentence under it: _Both chat rooms are linked._ ?

**Comment by MaxSemenchuk** [comment]
Maybe you can do a small drawing over a screenshot? =)
I can also add chats to the navigation

**Comment by krrisis** [comment]
Sorry for late reply! No, no need to add 'chat' as well, just redirect join button to this part is fine. 

Ok, so I created the idea in PAINT! (seriously, for ol' times sake)

![image](https://user-images.githubusercontent.com/6533925/50397955-39de9500-0774-11e9-8401-ba46e06c8231.png)


Temporary text to put here 
The Aragon Decentralized Altruistic Community is all about you. So come and talk to us. Pick the chat tool (rocket or riot) you prefer, all rooms are bridged! 

Note: plz link rocket & riot in the text as well, next to the icons themselves (see links above)

**Comment by MaxSemenchuk** [comment]
@krrisis should it be the 2nd screen, just after the logo and space bg?

**Comment by krrisis** [comment]
see initial description, I'd say to put that block between the video and 'find us on social'?

**Comment by MaxSemenchuk** [comment]
@krrisis pls check

**Comment by krrisis** [comment]
hey @MaxSemenchuk looks good, thx, the following should still be changed (original q) : 

- you can redirect the top nav ànd the 'join' button to a #join section which you create lower on the page 

thx!

**Comment by MaxSemenchuk** [comment]
Should be fine now

**Comment by krrisis** [comment]
It is! thx
