### ISSUE TITLE
adding missing profiles in team 

### ISSUE THREAD

**Issue by krrisis** [AragonDAC/aragondac-website#9]
Below an updated order + changes to existing titles + extra links

1) Griff 
2) Daniel 
3) Chris 
4) Arthur --> **Developer** + links from sheet

5) RJ --> add image + links from sheet
6) Gabriel
7) Jeremy --> add image + links from sheet 
8) Max 

9) Eva --> add image + links from sheet 
10) Kris --> just **Communications**
11) Loie --> add image + links from sheet

**Comment by krrisis** [comment]
Woops one you missed, github for RJ (important one) https://github.com/perissology

**Comment by MaxSemenchuk** [comment]
ok, resolved
